### PR TITLE
ci(gitlab): refactor gitlab pipelines

### PR DESCRIPTION
**Pull request by douglasduteil**

### CODE REVIEW

**Comment by revolunet** [comment]
Should some of these variables be given by CI ? 

```
DOCKER_DRIVER: overlay2
DOCKER_HOST: tcp://localhost:2375	
DOCKER_VERSION: "18.06"	
IMAGE_INFRA_BASE_NAME: "infra/images-docker"	 
DEV_ENVIRONMENT_NAME: "dev.factory"	  
PROD_ENVIRONMENT_NAME: "incubateur"	  
```

**Comment by douglasduteil** [comment]
I think we can share in at [the CI Group level](https://gitlab.factory.social.gouv.fr/groups/SocialGouv/-/settings/ci_cd)
`DOCKER_DRIVER` and `DOCKER_HOST`

I don't know if the `DOCKER_VERSION` is a fct of gitlab ...
We can test docker@19 maybe

`IMAGE_INFRA_BASE_NAME` can be removed you think ?

`DEV_ENVIRONMENT_NAME` and `PROD_ENVIRONMENT_NAME` might disappear with Azure...

**Comment by revolunet** [comment]
at least common shared docker variables and environments which should be the same

we keep DOCKER_VERSION / IMAGE_INFRA_BASE_NAME

**Comment by douglasduteil** [comment]
Updated :)

**Comment by revolunet** [comment]
still :
DEV_ENVIRONMENT_NAME: "dev.factory"
PROD_ENVIRONMENT_NAME: "incubateur"

**Comment by douglasduteil** [comment]
Baa.... they ain't the same on Azure...

**Pull request merged**
